"""PatientFusion — all tunable constants, thresholds, and cited clinical
reference data. No logic lives here.

MANDATORY FRAMING: every patient record in this project is generated by
Synthea (MITRE's open-source synthetic patient population simulator).
No real patient data is used anywhere in this project. See README.md.
"""
from __future__ import annotations

import os

DEMO_MODE = os.environ.get("DEMO_MODE", "True") == "True"

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
RAW_DATA_DIR = os.path.join(BASE_DIR, "data", "raw")
SILO_DATA_DIR = os.path.join(BASE_DIR, "data", "silos")

SILO_FILES = {
    "primary_care": os.path.join(SILO_DATA_DIR, "primary_care.csv"),
    "pharmacy": os.path.join(SILO_DATA_DIR, "pharmacy.csv"),
    "labs": os.path.join(SILO_DATA_DIR, "labs.csv"),
    "er": os.path.join(SILO_DATA_DIR, "er.csv"),
}

# ---------------------------------------------------------------------------
# Entity resolution (adapted from GhostTrace's entity_resolver.py —
# corporate ownership name matching maps directly onto patient name+DOB
# matching; token-sort/token-set fuzzy technique is identical)
# ---------------------------------------------------------------------------
FUZZY_AUTO_MERGE_THRESHOLD = 92   # name similarity alone auto-merges above this AND DOB matches exactly
FUZZY_ADJUDICATE_THRESHOLD = 72   # below this, never merge; between here and auto-merge, DOB proximity decides
DOB_NEAR_MATCH_DAYS = 2           # transcription slip tolerance (single-digit day/month typo lands within a few days)

# ---------------------------------------------------------------------------
# Lab test normalization — maps a small internal key to the raw Synthea
# LOINC-derived DESCRIPTION strings that mean the same test. Synthea often
# emits both a "in Blood" and "in Serum or Plasma" variant for the same
# concept; both collapse to one key here.
# ---------------------------------------------------------------------------
LAB_TEST_MAP: dict[str, list[str]] = {
    "a1c": ["Hemoglobin A1c/Hemoglobin.total in Blood"],
    "glucose": [
        "Glucose [Mass/volume] in Blood",
        "Glucose [Mass/volume] in Serum or Plasma",
    ],
    "creatinine": [
        "Creatinine [Mass/volume] in Blood",
        "Creatinine [Mass/volume] in Serum or Plasma",
    ],
    "egfr": [
        "Glomerular filtration rate [Volume Rate/Area] in Serum or Plasma "
        "by Creatinine-based formula (MDRD)/1.73 sq M",
    ],
    "potassium": [
        "Potassium [Moles/volume] in Blood",
        "Potassium [Moles/volume] in Serum or Plasma",
    ],
    "total_cholesterol": ["Cholesterol [Mass/volume] in Serum or Plasma"],
    "ldl": ["Cholesterol in LDL [Mass/volume] in Serum or Plasma by Direct assay"],
    "hdl": ["Cholesterol in HDL [Mass/volume] in Serum or Plasma"],
    "triglycerides": ["Triglyceride [Mass/volume] in Serum or Plasma"],
    # inr is not produced by Synthea's public module set (no anticoagulation
    # monitoring module) — kept here so the monitoring-gap rule below is
    # demonstrably correct ("0 of N warfarin patients have any INR record")
    # rather than silently absent. See README "Known data limitations".
    "inr": ["INR in Platelet poor plasma by Coagulation assay"],
}

# ---------------------------------------------------------------------------
# Drug interaction rules — every pair below is a real, independently
# documented interaction (FDA Drug Safety Communication or a peer-reviewed
# systematic review), not an invented threshold. Matching is by case-
# insensitive substring against the medication DESCRIPTION field, gated on
# overlapping active date ranges.
# ---------------------------------------------------------------------------
DRUG_INTERACTIONS: list[dict] = [
    {
        "id": "warfarin_nsaid",
        "drug_a": "warfarin",
        "drug_b_any": ["ibuprofen", "naproxen"],
        "severity": "MAJOR",
        "mechanism": "NSAIDs impair platelet function and irritate the GI "
                      "mucosa on top of warfarin's anticoagulant effect, "
                      "substantially raising bleeding risk.",
        "citation": "Holbrook AM et al. \"Systematic overview of warfarin "
                     "and its drug and food interactions.\" Arch Intern "
                     "Med. 2005;165(10):1095-1106.",
    },
    {
        "id": "warfarin_aspirin",
        "drug_a": "warfarin",
        "drug_b_any": ["aspirin"],
        "severity": "MAJOR",
        "mechanism": "Aspirin's antiplatelet effect combined with "
                      "warfarin's anticoagulant effect is one of the "
                      "highest-risk combinations for major bleeding.",
        "citation": "Holbrook AM et al. \"Systematic overview of warfarin "
                     "and its drug and food interactions.\" Arch Intern "
                     "Med. 2005;165(10):1095-1106.",
    },
    {
        "id": "digoxin_verapamil",
        "drug_a": "digoxin",
        "drug_b_any": ["verapamil"],
        "severity": "MAJOR",
        "mechanism": "Verapamil inhibits P-glycoprotein-mediated renal "
                      "clearance of digoxin, raising serum digoxin levels "
                      "and the risk of digoxin toxicity.",
        "citation": "Lanoxin (digoxin) FDA Prescribing Information, "
                     "Drug Interactions section (P-glycoprotein inhibitors).",
    },
    {
        "id": "simvastatin_amlodipine",
        "drug_a": "simvastatin",
        "drug_b_any": ["amlodipine"],
        "severity": "MODERATE",
        "mechanism": "Amlodipine raises simvastatin exposure via weak "
                      "CYP3A4 inhibition, increasing myopathy/rhabdomyolysis "
                      "risk. FDA caps simvastatin at 20mg/day with "
                      "amlodipine co-therapy.",
        "citation": "FDA Drug Safety Communication (June 8, 2011): \"New "
                     "restrictions, contraindications, and dose limitations "
                     "for Zocor (simvastatin) to reduce the risk of muscle "
                     "injury.\"",
    },
    {
        "id": "opioid_benzodiazepine",
        "drug_a_any": ["oxycodone", "hydrocodone", "tramadol", "fentanyl", "morphine"],
        "drug_b_any": ["diazepam", "midazolam", "alprazolam", "lorazepam"],
        "severity": "MAJOR",
        "mechanism": "Combined CNS and respiratory depression; concurrent "
                      "use is associated with profound sedation, respiratory "
                      "depression, coma, and death.",
        "citation": "FDA Drug Safety Communication (Aug 31, 2016): \"FDA "
                     "warns about serious risks and death when combining "
                     "opioid pain or cough medicines with benzodiazepines\" "
                     "(class-wide boxed warning).",
    },
    {
        "id": "acei_arb_dual_raas",
        "drug_a": "lisinopril",
        "drug_b_any": ["losartan"],
        "severity": "MODERATE",
        "mechanism": "Dual RAAS blockade (ACE inhibitor + ARB together) "
                      "increases hyperkalemia and acute kidney injury risk "
                      "without added cardiovascular benefit.",
        "citation": "Mann JF et al. (ONTARGET investigators), \"Renal "
                     "outcomes with telmisartan, ramipril, or both.\" "
                     "Lancet. 2008;372(9638):547-553.",
    },
]

# ---------------------------------------------------------------------------
# Polypharmacy
# ---------------------------------------------------------------------------
POLYPHARMACY_THRESHOLD = 5  # concurrently active medications
POLYPHARMACY_CITATION = (
    "Masnoon N, Shakib S, Kalisch-Ellett L, Caughey GE. \"What is "
    "polypharmacy? A systematic review of definitions.\" BMC Geriatr. "
    "2017;17:230. (5+ concurrent medications is the most commonly used "
    "definition in the literature.)"
)

# ---------------------------------------------------------------------------
# Overdue screening flags — real USPSTF / ACC-AHA population guidelines.
# ---------------------------------------------------------------------------
SCREENING_RULES: list[dict] = [
    {
        "id": "diabetes_a1c",
        "test_key": "a1c",
        "min_age": 35,
        "max_age": 70,
        "interval_days": 3 * 365,
        "label": "Diabetes screening (Hemoglobin A1c)",
        "citation": "USPSTF (2021), \"Screening for Prediabetes and Type 2 "
                     "Diabetes\", Grade B: adults 35-70 with overweight/"
                     "obesity, every 3 years. (Overweight/obesity status is "
                     "not modeled in this demo dataset; age band applied "
                     "alone — see README.)",
    },
    {
        "id": "lipid_panel",
        "test_key": "total_cholesterol",
        "min_age": 20,
        "max_age": None,
        "interval_days": 5 * 365,
        "label": "Lipid panel",
        "citation": "2018 AHA/ACC/AACVPR/AAPA/ABC/ACPM/ADA/AGS/APhA/ASPC/"
                     "NLA/PCNA Guideline on the Management of Blood "
                     "Cholesterol: lipid panel every 4-6 years for average-"
                     "risk adults >=20 without known ASCVD.",
    },
]

# ---------------------------------------------------------------------------
# Drug-specific monitoring requirements — a medication that clinically
# requires a periodic lab check. This is the rule that powers queries like
# "show me everyone on warfarin without a recent INR check."
# ---------------------------------------------------------------------------
# Fallback lookback window for ad-hoc natural-language queries whose
# drug+lab pair isn't one of the curated MONITORING_REQUIREMENTS below
# (e.g. a query about a drug/lab combination with no specific published
# monitoring interval). This is a UX default for "recent", not a clinical
# threshold -- when a real cited interval exists (below), that's used
# instead.
DEFAULT_LOOKBACK_DAYS = 365

MONITORING_REQUIREMENTS: list[dict] = [
    {
        "id": "warfarin_inr",
        "drug": "warfarin",
        "test_key": "inr",
        "interval_days": 30,
        "citation": "CHEST 2012 Antithrombotic Therapy Guidelines: INR "
                     "should be checked at least every 4 weeks in "
                     "stable patients on warfarin.",
    },
    {
        "id": "metformin_renal_function",
        "drug": "metformin",
        "test_key": "egfr",
        "interval_days": 365,
        "citation": "American Diabetes Association, Standards of Care in "
                     "Diabetes: renal function (eGFR) should be assessed "
                     "at least annually in patients on metformin.",
    },
]

# ---------------------------------------------------------------------------
# Readmission risk — simplified adaptation of the LACE index. LACE is a
# real, validated instrument; this implementation simplifies the
# comorbidity component to a presence-count over a curated condition list
# rather than the full weighted Charlson score. That simplification is
# disclosed here and in the README, not hidden.
# ---------------------------------------------------------------------------
LACE_CITATION = (
    "van Walraven C et al. \"Derivation and validation of an index to "
    "predict early death or unplanned readmission after discharge from "
    "hospital to the community.\" CMAJ. 2010;182(6):551-557. "
    "(Comorbidity component here is simplified to a presence-count over "
    "a curated Charlson-category keyword list, not the full weighted "
    "Charlson Comorbidity Index — see README.)"
)

# Length-of-stay (days) -> LACE "L" points
LACE_LOS_POINTS = [
    (0, 0), (1, 1), (2, 2), (3, 3), (6, 4), (13, 5),
]
LACE_LOS_POINTS_MAX = 7  # >=14 days

LACE_ACUTE_ADMISSION_POINTS = 3  # index encounter class == emergency
LACE_ED_VISIT_LOOKBACK_DAYS = 180
LACE_ED_VISIT_POINTS_CAP = 4      # >=4 prior ED visits in 6 months

# Charlson-category keyword list (Charlson ME et al., J Chronic Dis 1987;
# Quan H et al., Med Care 2005 ICD-10 adaptation) matched against
# condition DESCRIPTION strings, case-insensitive substring.
CHARLSON_KEYWORDS = [
    "diabetes", "chronic obstructive pulmonary disease", "copd",
    "congestive heart failure", "heart failure", "chronic kidney disease",
    "renal disease", "myocardial infarction", "cerebrovascular",
    "stroke", "dementia", "peripheral vascular disease", "malignant neoplasm",
    "carcinoma", "liver disease", "cirrhosis", "rheumatoid arthritis",
    "peptic ulcer", "hemiplegia", "hiv", "acquired immune deficiency",
]
LACE_COMORBIDITY_POINTS_CAP = 3  # 3+ Charlson-keyword conditions

LACE_RISK_TIERS = [
    (4, "LOW"),
    (9, "MODERATE"),
]
LACE_RISK_TIER_DEFAULT = "HIGH"  # score >= 10

# ---------------------------------------------------------------------------
# Claude — natural-language search interpretation only. Claude never scores
# or decides; it converts a free-text query into a structured filter that
# deterministic code executes ("Claude extracts, rules decide").
# ---------------------------------------------------------------------------
CLAUDE_MODEL = "claude-haiku-4-5-20251001"
