"""PatientFusion CLI — fuzzy patient-record linkage across four fragmented
health-record silos, built entirely on Synthea-generated SYNTHETIC data.

SYNTHETIC DATA ONLY. This is a data-fusion technique demonstration, not a
clinical decision support tool. See README.md.
"""
from __future__ import annotations

import os
import sys
from datetime import date

import click

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from claude_adjudicator import adjudicate
from config import DEMO_MODE
from dashboard import (
    console,
    print_banner,
    print_json,
    print_patient_timeline,
    print_population_heatmap,
    print_resolve_stats,
    print_search_results,
)
from linkage import build_master_patients
from nlsearch import execute_filter, parse_query
from risk_engine import evaluate_patient, population_heatmap_rows

_cache: dict = {}


def _get_patients(use_adjudicator: bool = True):
    key = "adjudicated" if use_adjudicator else "raw"
    if key not in _cache:
        adjudicator = adjudicate if use_adjudicator else None
        _cache[key] = build_master_patients(adjudicator)
    return _cache[key]


@click.group()
def cli() -> None:
    """
    PatientFusion: fuzzy name+DOB record linkage across four fragmented
    synthetic health-record silos (primary care, pharmacy, labs, ER).

    \b
    SYNTHETIC DATA ONLY -- every patient is generated by Synthea (MITRE's
    open-source synthetic patient population simulator). This is a data-
    fusion technique demonstration, NOT a real clinical decision support
    tool. Nothing here should inform real patient care.

    \b
    Data source: https://synthetichealth.github.io/synthea-sample-data/
    Entity resolution reuses GhostTrace's (P6) token-sort/token-set fuzzy
    matching, adapted from corporate ownership chains to patient records.
    """


@cli.command()
@click.option("--no-adjudicate", is_flag=True, help="Disable the adjudicator (name+DOB gating only).")
def resolve(no_adjudicate: bool) -> None:
    """Show cross-silo entity resolution statistics."""
    print_banner()
    _, stats = _get_patients(use_adjudicator=not no_adjudicate)
    print_resolve_stats(stats)
    if DEMO_MODE:
        console.print("[dim]DEMO_MODE=True -- adjudicator uses a deterministic heuristic, not a live Claude call.[/dim]")


@cli.command(name="list")
@click.option("--limit", type=int, default=25, help="Number of patients to show.")
def list_patients(limit: int) -> None:
    """List resolved master patients (to find a --patient-id for `timeline`)."""
    print_banner()
    patients, _ = _get_patients()
    console.print(f"[bold]{len(patients)}[/bold] master patients resolved. Showing first {limit}:")
    for p in patients[:limit]:
        console.print(f"  {p.patient_id}  {p.full_name:<25}  DOB {p.dob}  {', '.join(p.silos_present)}")


@cli.command()
@click.argument("patient_id")
def timeline(patient_id: str) -> None:
    """Show one patient's cross-silo timeline and decision-layer findings."""
    print_banner()
    patients, _ = _get_patients()
    patient = next((p for p in patients if p.patient_id == patient_id), None)
    if patient is None:
        console.print(f"[red]No patient with ID {patient_id}. Try `patientfusion list`.[/red]")
        raise SystemExit(1)
    findings = evaluate_patient(patient)
    print_patient_timeline(patient, findings)


@cli.command()
@click.option("--top", type=int, default=20, help="Show only the top N by readmission risk.")
@click.option("--format", "fmt", type=click.Choice(["table", "json"]), default="table")
def heatmap(top: int, fmt: str) -> None:
    """Population risk heatmap: readmission risk, interactions, polypharmacy."""
    patients, _ = _get_patients()
    rows = population_heatmap_rows(patients)
    if fmt == "json":
        print_json(rows)
    else:
        print_banner()
        print_population_heatmap(rows, top_n=top)


@cli.command()
@click.argument("query")
def search(query: str) -> None:
    """Natural-language population search, e.g.:

    \b
    patientfusion search "show me everyone on warfarin without a recent INR check"
    patientfusion search "patients on metformin without a recent eGFR check"
    """
    print_banner()
    patients, _ = _get_patients()
    filt = parse_query(query)
    results = execute_filter(patients, filt)
    print_search_results(query, filt.to_dict(), results)
    if DEMO_MODE:
        console.print("[dim]DEMO_MODE=True -- query parsed with a deterministic keyword matcher, not a live Claude call.[/dim]")


@cli.command()
def demo() -> None:
    """Run every PatientFusion feature against the seeded Synthea demo data."""
    print_banner()
    patients, stats = _get_patients()

    console.rule("[bold]Demo 1: Entity Resolution Across Silos[/bold]")
    print_resolve_stats(stats)

    console.rule("[bold]Demo 2: Population Risk Heatmap (Top 15)[/bold]")
    rows = population_heatmap_rows(patients)
    print_population_heatmap(rows, top_n=15)

    console.rule("[bold]Demo 3: Highest-Risk Patient Timeline[/bold]")
    ranked = sorted(rows, key=lambda r: r["lace_score"] or -1, reverse=True)
    top_patient = next(p for p in patients if p.patient_id == ranked[0]["patient_id"])
    print_patient_timeline(top_patient, evaluate_patient(top_patient))

    console.rule("[bold]Demo 4: Natural-Language Search -- warfarin / INR[/bold]")
    filt = parse_query("show me everyone on warfarin without a recent INR check")
    results = execute_filter(patients, filt)
    print_search_results("show me everyone on warfarin without a recent INR check", filt.to_dict(), results)
    console.print(
        "[dim]Note: Synthea's public module set does not generate INR/coagulation "
        "labs, so this query correctly returns every warfarin patient in the "
        "demo dataset -- a real data-coverage limitation, not a bug. See README, "
        "\"Known data limitations.\"[/dim]"
    )

    console.rule("[bold]Demo 5: Natural-Language Search -- metformin / eGFR[/bold]")
    filt2 = parse_query("patients on metformin without a recent eGFR check")
    results2 = execute_filter(patients, filt2)
    print_search_results("patients on metformin without a recent eGFR check", filt2.to_dict(), results2)

    console.print()
    console.print("[dim]DEMO_MODE=True -- all output above uses seeded synthetic data.[/dim]")


if __name__ == "__main__":
    cli()
